version: '3.8'

services:
  # Ansible Controller - where tests are executed from
  ansible-controller:
    build:
      context: .
      dockerfile: ansible_test_dockerfile
    image: devlama-ansible-controller:latest
    container_name: devlama-ansible-controller
    volumes:
      - ../../ansible_tests:/app/ansible_tests
      - ./ansible.cfg:/etc/ansible/ansible.cfg
      - ./inventory:/app/inventory
      - ./reports:/app/reports
    environment:
      - ANSIBLE_CONFIG=/etc/ansible/ansible.cfg
      - SHELLAMA_API_URL=http://shellama-target:19002
      - APILAMA_API_URL=http://apilama-target:19080
      - GETLLM_API_URL=http://getllm-target:19001
      - BEXY_API_URL=http://bexy-target:19000
      - DEVLAMA_API_URL=http://devlama-target:19003
    networks:
      - ansible-test-network
    depends_on:
      - shellama-target
      - apilama-target
    command: "sleep infinity"

  # SheLLama Target - service being tested
  shellama-target:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: shellama-test:latest
    container_name: shellama-target
    environment:
      - PORT=19002
      - HOST=0.0.0.0
      - DEBUG=true
    ports:
      - "19002:19002"
    volumes:
      - ../../:/app
    networks:
      - ansible-test-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # APILama Target - gateway service
  apilama-target:
    build:
      context: ../../../apilama
      dockerfile: Dockerfile
    image: apilama-test:latest
    container_name: apilama-target
    environment:
      - PORT=19080
      - HOST=0.0.0.0
      - DEBUG=true
      - SHELLAMA_API_URL=http://shellama-target:19002
      - GETLLM_API_URL=http://getllm-target:19001
      - BEXY_API_URL=http://bexy-target:19000
      - DEVLAMA_API_URL=http://devlama-target:19003
    ports:
      - "19080:19080"
    networks:
      - ansible-test-network
    depends_on:
      - shellama-target
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Mock PyLLM Target - for testing integration
  getllm-target:
    build:
      context: .
      dockerfile: mock_service_dockerfile
    image: mock-getllm:latest
    container_name: getllm-target
    environment:
      - SERVICE_NAME=getllm
      - PORT=19001
      - HOST=0.0.0.0
    ports:
      - "19001:19001"
    networks:
      - ansible-test-network

  # Mock BEXY Target - for testing integration
  bexy-target:
    build:
      context: .
      dockerfile: mock_service_dockerfile
    image: mock-bexy:latest
    container_name: bexy-target
    environment:
      - SERVICE_NAME=bexy
      - PORT=19000
      - HOST=0.0.0.0
    ports:
      - "19000:19000"
    networks:
      - ansible-test-network

  # Mock PyLama Target - for testing integration
  devlama-target:
    build:
      context: .
      dockerfile: mock_service_dockerfile
    image: mock-devlama:latest
    container_name: devlama-target
    environment:
      - SERVICE_NAME=devlama
      - PORT=19003
      - HOST=0.0.0.0
    ports:
      - "19003:19003"
    networks:
      - ansible-test-network

networks:
  ansible-test-network:
    driver: bridge

volumes:
  reports:
    driver: local
