---
# Wrapper playbook for running File operations tests

- name: Run File Operations Tests
  hosts: localhost
  gather_facts: false
  vars:
    shellama_base_url: "{{ lookup('env', 'SHELLAMA_URL') | default('http://localhost:5000/api/shellama', true) }}"
    test_directory: "/tmp/shellama_test"
    test_file: "/tmp/shellama_test/test_file.txt"
    test_content: "This is a test file created by Ansible"
    cleanup_enabled: "{{ lookup('env', 'CLEANUP_ENABLED') | default('true', true) }}"
    generate_report: "{{ lookup('env', 'GENERATE_REPORT') | default('true', true) }}"
  
  tasks:
    - name: Create test directories if they don't exist
      file:
        path: "{{ test_directory }}"
        state: directory
        mode: '0755'

    # Include File Operations Tests
    - name: Include File Operations Tests
      include_tasks: file_operations_tests.yml

    # Cleanup
    - name: Clean up test directories
      file:
        path: "{{ test_directory }}"
        state: absent
      when: cleanup_enabled | bool
