---
# SheLLama Test Playbook
# This playbook tests all endpoints of the SheLLama service

- name: Test SheLLama Endpoints
  hosts: localhost
  gather_facts: false
  vars:
    shellama_base_url: "{{ lookup('env', 'SHELLAMA_URL') | default('http://localhost:8002', true) }}"
    test_directory: "/tmp/shellama_test"
    test_file: "/tmp/shellama_test/test_file.txt"
    test_content: "This is a test file created by Ansible"
    git_test_dir: "/tmp/shellama_git_test"
  
  tasks:
    - name: Create test directories if they don't exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ test_directory }}"
        - "{{ git_test_dir }}"

    # Health Check Tests
    - name: Test Health Check Endpoint
      uri:
        url: "{{ shellama_base_url }}/health"
        method: GET
        return_content: yes
        status_code: 200
      register: health_result
      failed_when: health_result.json.status != "ok"

    - name: Display Health Check Result
      debug:
        var: health_result.json

    # Include test files for different service endpoints
    - name: Include File Operations Tests
      include_tasks: file_operations_tests.yml

    - name: Include Directory Operations Tests
      include_tasks: directory_operations_tests.yml

    - name: Include Shell Operations Tests
      include_tasks: shell_operations_tests.yml

    - name: Include Git Operations Tests
      include_tasks: git_operations_tests.yml

    - name: Include Error Handling Tests
      include_tasks: error_handling_tests.yml

    # Cleanup
    - name: Clean up test directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ test_directory }}"
        - "{{ git_test_dir }}"
      when: cleanup_enabled | default(true)

    # Generate Test Report
    - name: Include report generation playbook
      include_tasks: generate_report.yml
      when: generate_report | default(true)
